---

- name: "Create {{ lab_namespace }} Namespace"
  kubernetes.core.k8s:
    state: present
    template: namespace.yml.j2

- name: Set VM SSH Public Key When Credential Provided
  ansible.builtin.set_fact:
    vm_ssh_public_key: "{{ ssh_public_key }}"
  when: ssh_public_key is defined and ssh_public_key|length > 0

- name: Verify SSH public key is available
  ansible.builtin.assert:
    that:
      - vm_ssh_public_key is defined
      - vm_ssh_public_key | length > 0
    fail_msg: "'vm_ssh_public_key' is not defined"
    quiet: true


- name: Set cloud-init fact
  ansible.builtin.set_fact:
    cloud_init_content: |
      #cloud-config
      user: cloud-user
      ssh_authorized_keys:
        - {{ vm_ssh_public_key }}

- name: Create cloud-init Secret
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      type: Generic
      metadata:
        name: "{{ cloud_init_secret }}"
        namespace: "{{ lab_namespace }}"
      data:
        userdata: "{{ cloud_init_content | b64encode }}"

- name: "Create VirtualMachine"
  kubernetes.core.k8s:
    state: present
    template: virtualmachine.yml.j2

- name: Wait for VM to be ready
  kubernetes.core.k8s_info:
    api_version: kubevirt.io/v1
    kind: VirtualMachine
    name: "{{ lab_name }}"
    namespace: "{{ lab_namespace }}"
  register: lab_vm
  retries: 60
  delay: 10
  until:
  - lab_vm.resources[0].status is defined
  - lab_vm.resources[0].status.ready is true

- name: Wait for VM IP to be populated
  kubernetes.core.k8s_info:
    api_version: kubevirt.io/v1
    kind: VirtualMachineInstance
    name: "{{ lab_name }}"
    namespace: "{{ lab_namespace }}"
  register: lab_vmi
  retries: 60
  delay: 10
  until: (lab_vmi.resources[0].status.interfaces[0]['ipAddress'] | default('')) | length > 0

- name: Wait for SSH Connection to be ready
  ansible.builtin.wait_for:
    host: "{{ lab_vmi.resources[0].status.interfaces[0]['ipAddress'] }}"
    port: 22

- name: "Create Service"
  kubernetes.core.k8s:
    state: present
    template: service.yml.j2

- name: "Create Route"
  kubernetes.core.k8s:
    state: present
    template: route.yml.j2