- hosts: localhost
  gather_facts: false
  connection: local
  collections:
    - redhat_cop.controller_configuration
  tasks:
    - name: Include vars
      ansible.builtin.include_vars: "{{ playbook_dir }}/../vars/{{ provision_var_file | default('provision.yml') }}"

    - name: Configure AAP
      ansible.builtin.include_role:
        name: configure-aap
        tasks_from: configure-ocp.yml
