---        
name: CI   
           
on:        
  pull_request:
  push:    
    branches:
      - main
           
jobs:      
  test:    
    name: molecule
    runs-on: ubuntu-latest
           
    steps: 
      - name: Checkout the codebase.
        uses: actions/checkout@v2
           
      - name: Set up Python3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
           
      - name: Install yamllint, ansible and molecule
        run: |
          python -m pip install --upgrade pip
          pip install yamllint 'molecule[docker]==3.5.2' ansible-core flake8 ansible-lint voluptuous
          ansible-galaxy collection install -r requirements.yml

      - name: Run linter
        run: |
          ansible-lint --version
          ansible-lint -v