---        
name: CI   
           
on:        
  pull_request:
  push:    
    branches:
      - main

env:
  COLORTERM: 'yes'
  TERM: 'xterm-256color'
  PYTEST_ADDOPTS: '--color=yes'

jobs:      
  test:    
    name: CI test
    runs-on: ubuntu-latest
           
    steps: 
      - name: Checkout the codebase.
        uses: actions/checkout@v2
           
      - name: Set up Python3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
           
      - name: Install yamllint
        run: |
          python -m pip install --upgrade pip
          pip install yamllint ansible-core ansible-lint
          ansible-galaxy collection install kubernetes.core

      - name: Run linter
        run: |
          ansible-lint --version
          ansible-lint --offline